### ISSUE TITLE
Searching by Chained parameters not working as expected

### ISSUE THREAD

**Issue by yosbeleg89** [Aidbox/Issues#11]
When doing a query like:

GET `/fhir/Patient?general-practitioner.identifier=someidentifier`

it is returning an error like:

`{:status :error, :errors [{:type :error, :message "No search parameter for Patient.general-practitioner.identifier"}]}`

According to the FHIR docs it should return the patients that have a General Practitioner that contains such identifier.

**Comment by yosbeleg89** [comment]
Now I added the resource type and the request executed succesfully, but no results were returned. Tried to add the system and got the same result.

**Comment by mlapshin** [comment]
works in recent aidbox versions (I'm not sure when exactly it was fixed):

```
GET /fhir/Patient/42

name:
- given: [Forty two]
id: '42'
meta:
  lastUpdated: '2018-11-30T15:01:52.814Z'
  versionId: '254'
  tag:
  - {system: 'https://aidbox.app', code: updated}
generalPractitioner:
- {reference: Practitioner/pract1}
resourceType: Patient
```

```
GET /fhir/Practitioner/pract1

qualification:
- code:
    text: Bachelor of Science
    coding:
    - {code: BS, system: 'http://hl7.org/fhir/v2/0360/2.7', display: Bachelor of Science}
  period: {start: '1995'}
  identifier:
  - {value: '12345', system: 'http://example.org/UniversityIdentifier'}
  issuer: {display: Example University}
id: pract1
name:
- given: [Adam]
  family: Careful
  prefix: [Dr]
address:
- use: home
  city: PleasantVille
  line: [534 Erewhon St]
  state: Vic
  postalCode: '3999'
text: {div: "<div xmlns=\"http://www.w3.org/1999/xhtml\">\n      <p>Dr Adam Careful\
    \ is a Referring Practitioner for Acme Hospital from 1-Jan 2012 to 31-Mar\n  \
    \      2012</p>\n    </div>", status: generated}
identifier:
- {value: '23', system: 'http://www.acme.org/practitioners'}
meta:
  lastUpdated: '2018-11-30T15:00:03.269Z'
  versionId: '253'
  tag:
  - {system: 'https://aidbox.app', code: created}
active: true
resourceType: Practitioner
```

```
GET /fhir/Patient?general-practitioner:Practitioner.identifier=23

entry:
- resource:
    name:
    - given: [Forty two]
    id: '42'
    meta:
      lastUpdated: '2018-11-30T15:01:52.814Z'
      versionId: '254'
      tag:
      - {system: 'https://aidbox.app', code: updated}
    generalPractitioner:
    - {reference: Practitioner/pract1}
    resourceType: Patient
  fullUrl: http://mlapshin.127.0.0.1.xip.io:8080/Patient/42
resourceType: Bundle
type: searchset
```
