### ISSUE TITLE
Allow interpolation from request object's data with "static" SQL parts

### ISSUE THREAD

**Issue by yosbeleg89** [Aidbox/Issues#115]
In the SQL AccessPolicy definition we need to interpolate data from the request with SQL "static" parts like table names. When trying to do something like this:

```SQL
SELECT resource FROM public."{{params.resource/type}}"
```

Aidbox is unable to successfully execute that SQL to evaluate the corresponding AccessPolicy.

**Comment by niquola** [comment]
With deploy 0.4.5-SNAPSHOT you will be able todo this with `{{!<expr>}}`:

```sql
SELECT resource FROM {{!params.resource/type}}
```

**Comment by niquola** [comment]
As well I created new endpoint to debug policy without creating it - I will document it tomorrow in aidbox docs.  Here is short description:

```yaml
POST /auth/test-policy

request:
  uri: '/Patient'
  request-method: get
 -- or user-id
  user:
    role: admin
policy:
  engine: sql
  sql:
    query: 'SELECT {{user.role}} FROM {{!params.resource/type}}'

-- resp

request:
  uri: /Patient
  request-method: get
  user: {role: admin}
  params: {resource/type: Patient}
operation:
  request:
  - get
  - {name: resource/type}
  action: proto.operations/search
  module: proto
  id: Search
  w: null
policy:
  engine: sql
  sql: {query: 'SELECT {{user.role}} FROM {{!params.resource/type}}'}
result:
  eval-result: null
  query: ['SELECT ? FROM "patient"', admin]
```
