### ISSUE TITLE
JUTE error in conditions for boolean value

### ISSUE THREAD

**Issue by ruscoder** [Aidbox/Issues#119]
When I use mapping with this content:
```
body:
  entry:
    - request:
        url: /MyResource
        method: POST
      resource:
        resourceType: MyResource
        payload:
          active:
            $if: '$ Inactive_Flag = true'
            $else: true
            $then: false
```

For data: `{"Inactive_Flag": false}` everything is OK, but for `{"Inactive_Flag": true}` I have

```
resourceType: MyResource
  payload:
    active: {$else: true}
```

**Comment by ruscoder** [comment]
Also, this Mapping works wrong for `{"Inactive_Flag": true}` - key `active` disappears

```
body:
  entry:
    - request:
        url: /MyResource
        method: POST
      resource:
        resourceType: MyResource
        payload:
          active: $ Inactive_Flag = "True"
```
