### ISSUE TITLE
References does not get translated on custom attributes

### ISSUE THREAD

**Issue by yosbeleg89** [Aidbox/Issues#135]
On custom attributes, if created one of type reference and post a reference using FHIR references (FHIR endpoint) then when fetching the entity using aidbox endpoint it returns the FHIR reference, the same thing happens the other way around, if posted with aidbox references (Aidbox endpoint) then when fetching using FHIR endpoint it returns aidbox references.

If it is also created a SearchParameter for that attribute then it only works when the resource was posted with aidbox references.

**Comment by niquola** [comment]
can you provide definition of attribute?

**Comment by yosbeleg89** [comment]
@niquola

```yaml
    description: Some description
    path: [owner]
    refers: [Practitioner, PractitionerRole, Organization, Patient]
    type: {id: Reference, resourceType: Entity}
    resourceType: Attribute
    module: mymodule
    id: MyCustomEntity.owner
    resource: {id: MyCustomEntity, resourceType: Entity}
    isRequired: true
```
