### ISSUE TITLE
Can not use search by money

### ISSUE THREAD

**Issue by ruscoder** [Aidbox/Issues#148]
I have `Invoice` resource:
```
resourceType: Invoice
...
totalGross:
  value: 2625.0
  currency: USD
```

I can't search by `totalgross` search param:
```
GET /Invoice?totalgross=2500
```

```
ERROR: Could not extract as number {"value": 2625.0, "currency": "USD"}'}
```
