### ISSUE TITLE
Wrong FHIR transformation for extension attribute with isCollection: true

### ISSUE THREAD

**Issue by ruscoder** [Aidbox/Issues#159]
Hello!
I've created an attribute with `extensionUrl: "http://hl7.org/fhir/StructureDefinition/event-note"` and `isCollection: true`.

After creating the resource with:
```
note:
  - text: hello1
  - text: hello2
```

the /fhir/ endpoint generates the following output:
```
extension:
- url: http://hl7.org/fhir/StructureDefinition/event-note
  valueAnnotation:
  - {text: hello1}
  - {text: hello2}
```
that is not valid.  
I suppose it should be handled as multiple entries of the extension with the same URL:

```
extension:
- url: http://hl7.org/fhir/StructureDefinition/event-note
  valueAnnotation:
    text: hello1
- url: http://hl7.org/fhir/StructureDefinition/event-note
  valueAnnotation:
    text: hello2
```

@niquola What do you think about it?
