### ISSUE TITLE
200 ok in case of error on PUT /

### ISSUE THREAD

**Issue by vganshin** [Aidbox/Issues#160]
<img width="871" alt="Screenshot 2019-09-12 at 16 20 48" src="https://user-images.githubusercontent.com/1931520/64787605-9e978500-d579-11e9-8690-f62ce65b6d8e.png">

The resource wasn't created. 

```yaml
PUT /

-   id: list-4
    resourceType: List
    status: "Generated"
    mode: "changes"
    subject: 
      resourceType: "Patient"
      id: "pt-2"
    entry:
    - item:
      resourceType: "Patient"
      id: "pt-1"
    - item:
      resourceType: "Patient"
      id: "pt-3"

```
