### ISSUE TITLE
Unobvious error message when required param wasn't defined for SearchQuery

### ISSUE THREAD

**Issue by vganshin** [Aidbox/Issues#165]
I created sample SearchQuery resource from the doc.
```yaml
PUT /SearchQuery/q-2

resource: {id: 'Encounter', resourceType: 'Entity'}
as: enc
query:
  order-by: pt.id desc
params:
   pt:
     type: string
     format: '% ?%'
     join:
       pt: 
         table: patient
         by: "enc.resource#>>'{subject,id}' = pt.id"
     where: |
        aidbox_text_search(knife_extract_text(pt.resource, $$[["name","family"]]$$)) 
        ilike {{params.pt}}
```

Then I wanted to use the query and got 500.
```yaml
GET /alpha/Encounter?query=q-2

Response:
resourceType: OperationOutcome
id: exception
text:
  status: generated
  div: |-
    ERROR: missing FROM-clause entry for table "pt"
      Position: 40
issue:
- severity: fatal
  code: exception
  diagnostics: |-
    ERROR: missing FROM-clause entry for table "pt"
      Position: 40
```

It'd be great to see more convenient error message telling that `pt` param is required.
