### ISSUE TITLE
SearchQuery doesn't validate resourceType on GET

### ISSUE THREAD

**Issue by vganshin** [Aidbox/Issues#166]
Tested on stresty 0.0.12
```yaml
steps:
- id: create-sq
  PUT: /SearchQuery/q-1
  body:
    # attach this query to Patient resource type
    resource: {id: 'Patient', resourceType: 'Entity'}
    # give alias to patient table
    as: pt
    # enable total query
    total: true 
    # basic query
    query:
      where: "(pt.resource->>'birthDate')::date > '1994-01-01'"
      order-by: pt.id desc
  match:
    status: 200

- id: use-sq-for-wrong-resource
  GET: /alpha/Wrong?query=q-1
  match:
    status: 4xx?
```
