### ISSUE TITLE
FHIR R4 Missing SearchParameter.expression for ValueSet.context

### ISSUE THREAD

**Issue by ruscoder** [Aidbox/Issues#170]
Aidbox 0.4.6

```
expression: []
name: context
type: token
resourceType: SearchParameter
source: code
module: fhir-4.0.0
id: ValueSet.context
resource:
  id: ValueSet
  resourceType: Entity
```

It leads to the error:
```
devbox-db_1  | 2019-09-19 04:26:27.097 UTC [26181] ERROR:  syntax error at or near ")" at character 44
devbox-db_1  | 2019-09-19 04:26:27.097 UTC [26181] STATEMENT:  SELECT "valueset".* FROM "valueset" WHERE () LIMIT $1 OFFSET $2
```
