### ISSUE TITLE
_summary returns elements that don't have isSummary attribute.

### ISSUE THREAD

**Issue by Virnkord** [Aidbox/Issues#171]
Create the patient resource:

```
PUT /Patient/patient01

resourceType: Patient
id: patient01
name:
  - given: [Petr]
    family: Aleksandrov
birthDate: '1983-04-30'
generalPractitioner:
  - id: pr-r1
    resourceType: Practitioner
language: "russian"
contact:
  - gender: "male"
```

The query is:

```
GET /Patient?_id=patient01&_summary=true
```
The response is:
```
resourceType: Bundle
type: searchset
entry:
- resource:
    name:
    - given: [Petr]
      family: Aleksandrov
    contact:
    - {gender: male}
    language: russian
    birthDate: '1983-04-30'
    generalPractitioner:
    - {id: pr-r1, resourceType: Practitioner}
    id: patient01
    resourceType: Patient
    meta: {lastUpdated: '2019-09-20T15:08:33.173303Z', versionId: '1361'}
  fullUrl: http://localhost:8888/Patient/patient01
total: 1
link:
- {relation: first, url: '/Patient?_id=patient01&_summary=true&page=1'}
- {relation: self, url: '/Patient?_id=patient01&_summary=true&page=1'}
query-sql: ['SELECT "patient".* FROM "patient" WHERE ("patient".id in (?)) LIMIT ? OFFSET ? ', patient01, 100, 0]
query-timeout: 60000
query-time: 1
```

So, the responce contains generalPractitioner, language and contact elements, but these elements hasn't isSummary attribute.
