### ISSUE TITLE
Problems retrieving the linked medications of a MedicationRequest

### ISSUE THREAD

**Issue by tangsl** [Aidbox/Issues#175]
Executing the following query don't return the linked medications for the respective MedicationRequest `GET /MedicationRequest?_include=medication`

### Example

Create the patient

```
POST /Patient

resourceType: Patient
id: pat1
name:
  - given: [Jon]
    family: Doe
birthDate: '1944-11-17'
language: "english"
contact:
  - gender: "male"
```

Create the medication

```
POST /Medication

resourceType: Medication
id: med1
code:
  text: Vancomycin Hydrochloride
status: active
form:
  text: Injection Solution
```

Create the medication request

```
POST /MedicationRequest

resourceType: MedicationRequest
intent: option
status: draft
id: medr1
medication:
  Reference: 
    resourceType: Medication
    id: med1
subject:
  resourceType: Patient
  id: pat1
```

The query

`GET /MedicationRequest?_include=medication`

Response

```
resourceType: Bundle
type: searchset
entry:
- resource:
    intent: option
    status: draft
    subject: {id: pat1, resourceType: Patient}
    medication:
      Reference: {id: med1, resourceType: Medication}
    id: medr1
    resourceType: MedicationRequest
    meta: {lastUpdated: '2019-09-23T21:14:34.109Z', versionId: '6'}
  fullUrl: http://localhost:8888/MedicationRequest/medr1
total: 1
link:
- {relation: first, url: '/MedicationRequest?_include=medication&page=1'}
- {relation: self, url: '/MedicationRequest?_include=medication&page=1'}
query-sql: ['SELECT "medicationrequest".* FROM "medicationrequest" LIMIT ? OFFSET ? ', 100, 0]
query-time: 10
```

No medication resources are included on the response. However when try to get all the linked resources, the medications appears

`GET /MedicationRequest?_include=*`

Response 

```
resourceType: Bundle
type: searchset
entry:
- resource:
    code: {text: Vancomycin Hydrochloride}
    form: {text: Injection Solution}
    status: active
    id: med1
    resourceType: Medication
    meta: {lastUpdated: '2019-09-23T21:14:24.037Z', versionId: '5'}
  fullUrl: http://localhost:8888/Medication/med1
- resource:
    name:
    - given: [Jon]
      family: Doe
    contact:
    - {gender: male}
    language: english
    birthDate: '1944-11-17'
    id: pat1
    resourceType: Patient
    meta: {lastUpdated: '2019-09-23T21:14:14.709Z', versionId: '4'}
  fullUrl: http://localhost:8888/Patient/pat1
- resource:
    intent: option
    status: draft
    subject: {id: pat1, resourceType: Patient}
    medication:
      Reference: {id: med1, resourceType: Medication}
    id: medr1
    resourceType: MedicationRequest
    meta: {lastUpdated: '2019-09-23T21:14:34.109Z', versionId: '6'}
  fullUrl: http://localhost:8888/MedicationRequest/medr1
total: 1
link:
- {relation: first, url: '/MedicationRequest?_include=*&page=1'}
- {relation: self, url: '/MedicationRequest?_include=*&page=1'}
query-sql: ['SELECT "medicationrequest".* FROM "medicationrequest" LIMIT ? OFFSET ? ', 100, 0]
query-time: 15
```
