### ISSUE TITLE
Bug: _elements affects included resources

### ISSUE THREAD

**Issue by ruscoder** [Aidbox/Issues#208]
Example:
```
get /EpisodeOfCare?_include=EpisodeOfCare:patient&_elements=status,patient
```

Output:
```
resourceType: Bundle
type: searchset
entry:
- resource: {resourceType: Patient}
  fullUrl: https://vadimtest1.aidbox.app/Patient/
- resource:
    status: current
    patient: {id: test, resourceType: Patient}
    resourceType: EpisodeOfCare
  fullUrl: https://vadimtest1.aidbox.app/EpisodeOfCare/
total: 1
link:
- {relation: first, url: '/EpisodeOfCare?_include=EpisodeOfCare:patient&_elements=status,patient&page=1'}
- {relation: self, url: '/EpisodeOfCare?_include=EpisodeOfCare:patient&_elements=status,patient&page=1'}
query-sql: ['SELECT "episodeofcare".* FROM "episodeofcare" LIMIT ? OFFSET ? ', 100, 0]
query-timeout: 60000
query-time: 3
```

See https://www.hl7.org/fhir/search.html#elements

The _elements parameter consists of a comma-separated list of base element names such as, elements defined at the root level in the resource. Only elements that are listed are to be returned. Clients SHOULD list all mandatory and modifier elements in a resource as part of the list of elements. **The list of elements does not apply to included resources.**
