### ISSUE TITLE
"unacceptable kind of an object to dump [object Error]" in Mapping editor

### ISSUE THREAD

**Issue by vganshin** [Aidbox/Issues#210]
The following request returns empty body. 
```
POST /Mapping/$debug

scope:
  codeSystem: icd-10
  code: E10
mapping:
  body:
    code:
      system: diabet-type
      code:
        "$switch": "$ codeSystem"
        my-system:
          "$let":
            mySystemToDiabetTypeMap:
              '123': type-2
          "$body":
            type: "$ mySystemToDiabetTypeMap.(code)"
  id: diabet-type-mapping
  resourceType: Mapping
```
Mapping editor fails with error (F12→Console):

> S-YAML: unacceptable kind of an object to dump [object Error]
