### ISSUE TITLE
Possible bug in SearchQuery

### ISSUE THREAD

**Issue by pavlushkin** [Aidbox/Issues#214]
**Precondition:**
There is an include statement in SearchQuery

```yaml
as: eoc
params:
  pt:
    join:
      pt:
        by: "eoc.resource#>>'{patient,id}' = pt.id"
        table: patient
    type: string
    where: "aidbox_text_search(knife_extract_text(pt.resource, $$[[\"name\",\"family\"]]$$)) \nilike {{params.pt}}\n"
    format: '%?%'
includes:
  patient:
    path:
      - patient
    resource:
      id: Patient
      resourceType: Entity
  documents:
    path:
      - context
      - encounter
    reverse: true
    resource:
      id: DocumentReference
      resourceType: Entity
resourceType: SearchQuery
total: true
id: q-1
resource:
  id: EpisodeOfCare
  resourceType: Entity
query:
  order-by: "eoc.resource#>>'{period,start}' desc"
```

**Action:**
`GET /alpha/EpisodeOfCare?query=q-1&pt=non_existing_text`
There is no such patient in db with `non_existing_text` in the family attribute.

**Expected behaviour:** 
There is an emty response.

**Actual behaviour:** 
There is a 500 server-side error.
```
error ERROR: syntax error at or near "NULL"
  Position: 137 w4 [1ms] SELECT * FROM "documentreference" WHERE ((knife_extract_text(resource, $$[["context","encounter",{"resourceType":null},"id"]]$$))[1] in NULL) LIMIT ? ["1000"]
```
