### ISSUE TITLE
Add an ability to filter included/revincluded resources in SearchQuery

### ISSUE THREAD

**Issue by pavlushkin** [Aidbox/Issues#216]
I use SearchQuery and try to revinclude DocumentReference resources; not all ones, but only with a particular type. Current SearchQuery syntax does not allow me to do that.

SearchQuery example
```
resourceType: SearchQuery
id: q-2
resource:
  id: EpisodeOfCare
  resourceType: Entity
as: eoc
params:
  dr:
    join:
      dr:
        by: "eoc.id = dr.resource#>> '{context, encounter, 0, id}' and dr.resource#>> '{type, coding, 0, code}' = {{params.dr}}"
        table: documentreference
    type: string
includes:
  documents:
    path:
      - context
      - encounter
    reverse: true
    resource:
      id: DocumentReference
      resourceType: Entity
query:
  order-by: "eoc.resource#>>'{period,start}' desc"
total: true
```

**Actual result:**
There are DocumentReference resources of all types revincluded using proper .context.encounter.
Using additional condition in “params, dr, join, dr, by” I can control only filtering of the main resource.

**Desired result:**
There are only revincluded DocumentReference resources with a provided type ( dr.resource#>> '{type, coding, 0, code}' = <provided in params type> ).

**Comment by niquola** [comment]
in progress - impl this tomorrow!

**Comment by niquola** [comment]
Now you have `where` key in include to add additional criteria for inclusion.
Be aware, that include is done by a separate query to the table you want to include.
This is not related to the main search query and joins!

```yaml
resourceType: SearchQuery
id: q-2
resource:
  id: EpisodeOfCare
  resourceType: Entity
as: eoc
params:
  dr:
    join:
      dr:
        by: "eoc.id = dr.resource#>> '{context, encounter, 0, id}'"
        table: documentreference
    type: string
includes:
  documents:
    path:
      - context
      - encounter
    reverse: true
    resource:
      id: DocumentReference
      resourceType: Entity
    where:  "resource#>> '{type, coding, 0, code}' = 'fixedCode'"
query:
  order-by: "eoc.resource#>>'{period,start}' desc"
total: true
```
