### ISSUE TITLE
Authentication issues in complex

### ISSUE THREAD

**Issue by kzotoff** [Aidbox/Issues#223]
First, I made 2 `Client`+`User` pairs, clients have full access:
**Client:**
```
auth:
  password:
    token_format: jwt
    refresh_token: true
secret: password
grant_types:
  - basic
  - password
  - refresh_token
id: test_client
resourceType: Client
```

**AccessPolicy:**
```
link:
  - id: test_client
    resourceType: Client
engine: allow
description: test user access
id: test-user-policy
resourceType: AccessPolicy
```

I use postman with first pair `Client`+`User` and AidBox console with the second. Both run on same computer, nobody more uses that credentials at the moment. Postman collection contains four requests: authentication, user info, token refresh, user info again.

00) Postman collection can be found here: https://gist.github.com/kzotoff/cf6753a2ee72fff28c51165321e5cba6
0) Set proper client and user credentials at postman collection first request pre-req section (first user)
1) Log second user to console
2) Run postman requests one by one
3) Refresh console

First issue: 2 and 4 postman requests shows different results, although they are same.
Second issue: console user no more logged in - any action will result 401 error can be seen at browser's network log
Third issue: `access_token` after refresh has not JWT format
