### ISSUE TITLE
Inconsistent and incorrect ValueSet expansion

### ISSUE THREAD

**Issue by vladdem** [Aidbox/Issues#236]
### Different behavior without $expand
Request
`GET /fhir/ValueSet/yesnodontknow`
returns result with populated `expansion` field, what unexpected, but similar request
`GET /fhir/ValueSet/administrative-gender`
returns result **without** `expansion` field as expected.

### Errors with $expand
Both requests
`GET /fhir/ValueSet/yesnodontknow/$expand`
`GET /fhir/ValueSet/administrative-gender/$expand`
returns error
```yaml
resourceType: OperationOutcome
id: not-found
text: {status: generated, div: Resource CompartmentDefinition/ValueSet not found}
issue:
- {severity: fatal, code: not-found, diagnostics: Resource CompartmentDefinition/ValueSet not found}
```
### Empty expansion
Request without `/fhir` prefix
`GET /ValueSet/administrative-gender/$expand`
returns no items in `expansion` field
```yaml
expansion:
  timestamp: 2020-01-16T13:17:58.777Z
  identifier: http://hl7.org/fhir/ValueSet/administrative-gender
  contains: {error: No results were returned by the query.}
```
