### ISSUE TITLE
Request with _elements parameter has fullUrl broken

### ISSUE THREAD

**Issue by kzotoff** [Aidbox/Issues#247]
If request contains __elements_ parameter not containing _id_, like this:
`GET /Appointment?_elements=supportingInformation`

response has _fullUrl_ field broken:
```
resourceType: Bundle
type: searchset
entry:
- resource:
    supportingInformation:
        ...
    resourceType: Appointment
  fullUrl: http://devbox:9080/Appointment/
...
```
