### ISSUE TITLE
AccessPolicy __debug=policy bug

### ISSUE THREAD

**Issue by mlapshin** [Aidbox/Issues#256]
```
PUT /AccessPolicy/isBundleOrHasAtLeastOneResource
engine: complex
or:
  - engine: json-schema
    schema:
      required: [uri, request-method]
      properties:
        uri: {const: '/fhir'}
        request-method: {const: post}
  - engine: sql
    sql:
      query: 'select true from {{!params.resource/type}} limit 1'
```

then a request like this (with postman/curl, not admin ui)

```
POST http://localhost:8080/fhir
{
	"resourceType": "Bundle",
	"type": "batch",
	"entry": [
		{
			"request": {
				"method": "get",
				"url": "/AccessPolicy?_count=0"
			}
		}
	]
}
```

succeeds, but if I add __debug=policy the result is

```
{
            "eval-result": null,
            "id": "isBundleOrHasAtLeastOneResource",
            "error": "AccessPolicy Error: no value at {{!params.type}}",
            "policy-id": "isBundleOrHasAtLeastOneResource"
        }
```
