### ISSUE TITLE
extension.value by aidbox endpoint use fhir polymorphic types instead aidbox ones

### ISSUE THREAD

**Issue by jyeros** [Aidbox/Issues#260]
When try to post

```
Put /Task/task1

intent: order
status: draft
input:
  - type:
      text: asd
    value:
      string: "111"
```
it works

and when try to post with fhir types

```
Put /Task/task1

intent: order
status: draft
input:
  - type:
      text: asd
    valueString: "111"


Status: 422
resourceType: OperationOutcome
text: {status: generated, div: Invalid resource}
issue:
- {severity: fatal, code: invalid, expression: Task.input.0.valueString, diagnostics: extra property}
```
it fail as expected

But it doesn't work this way inside extension property

for example with aidbox types

```
Put /Patient/pat1

extension:
  - url: http://temp
    value:
      string: "111"


Status: 422
resourceType: OperationOutcome
text: {status: generated, div: Invalid resource}
issue:
- {severity: fatal, code: invalid, expression: Patient.extension.0.value, diagnostics: extra property}
```

it fail even if I am trying to post by aidbox endpoint

But it works with fhir types 
```
Put /Patient/pat1

extension:
  - url: http://temp
    valueString: "111"
```
