### ISSUE TITLE
ResourceReference return property id by fhir endpoint

### ISSUE THREAD

**Issue by jyeros** [Aidbox/Issues#274]
When I post a resource by fhir endpoint with a property of type reference and specify only `reference` when do a get to this resource by fhir endpoint an extra property `id` is retorned, the resource is saved correct in db and showed well by aidbox endpoint

Example:

```
Put /fhir/Organization/org1

id: org1
resourceType: Organization



Put /fhir/Organization/org2

id: org1
resourceType: Organization
partOf:
  reference: Organization/org1
```

Then when i do
```
Get /fhir/Organization/org2
```
the response is
```
partOf: {id: org1, reference: Organization/org1}
id: org2
resourceType: Organization
meta:
  lastUpdated: '2020-03-11T23:00:03.398423Z'
  versionId: '2668'
  extension:
  - {url: 'ex:createdAt', valueInstant: '2020-03-11T23:00:03.398423Z'}
```
partOf has an extra property `id`

But in db it is well
```
select resource from organization where id = 'org2'

resource 
{
 "partOf": {
  "id": "org1",
  "resourceType": "Organization"
 }
}
```

If I post it by aidbox with aidbox format and get it by fhir the same happens 

`devbox; 0.4.9; bdf14e28`
