### ISSUE TITLE
Support custom operation for batch and bundle transaction

### ISSUE THREAD

**Issue by ir4y** [Aidbox/Issues#282]
I am using a batch bundle to perform multiple operations.  
If there is a custom operation from the app I always get an error.
```
{div: 'Transaction failed at entry[0]. Response status is . Response body is "/172.19.0.5:8080<->/172.19.0.1:58300"'}
```

**Comment by KGOH** [comment]
Couldn't reproduce. @ir4y what exactly is custom operation? Can you give an example of your post request, please?

**Comment by ir4y** [comment]
@KGOH 

I created aidbox app with https://github.com/aidbox/aidbox-python-sdk
I registered bulk delete operation
```python
@sdk.operation(["DELETE"], [{"name": "resource-name"}, "$force-delete"],
               public=True)
async def force_delete(operation, request):
    to_delete = await sdk.client.resources(request['route-params']['resource-name']).search(**request.get('params', {})).elements('id').fetch_all()
    if len(to_delete) > 0:
            Table = getattr(sdk.db, request['route-params']['resource-name'])
            await sdk.db.alchemy(
                Table.delete(returning=[Table.c.id]).where(Table.c.id.in_(i.id for i in to_delete)))
    status = 200
    return web.json_response({}, status=status)

```

If I call this operation from a bundle I got reported error
```
POST /

type: batch
resourceType: Bundle
entry:
- request: 
    url: '/NutritionOrder/$force-delete?patient=c2bf006e-8d50-46cb-925c-4555a971df1b'
    method: DELETE
```
