### ISSUE TITLE
:not modifers doesn't work for AllergyIntolerance code.

### ISSUE THREAD

**Issue by ir4y** [Aidbox/Issues#285]
If you create an AllergyIntolerance resource.
```
code:
  coding:
    - code: '165009005'
      system: 'http://snomed.info/sct'
      display: No Allergy
      version: 'http://snomed.info/sct/32506021000036107/version/20180930'
patient:
  id: 956859ab-df46-4610-8180-a03b4c065b17
  resourceType: Patient
id: 978c10f1-4e9a-48d8-8b12-a4b95bfba0dd
resourceType: AllergyIntolerance
```
and try to find AllergyIntolerance that does not have code 165009005 with a query
```
GET /AllergyIntolerance/?code:not=165009005
```
You will  get original resource in the result bundle.

I caused by wrong SQL generation when you have `:not` modifier and multiple paths in SearchParameter.
