### ISSUE TITLE
Reverse includes don't work in SearchQuery

### ISSUE THREAD

**Issue by jdim** [Aidbox/Issues#297]
Hi folks,  I'm stuck writing [SearchQuery](https://docs.aidbox.app/basic-concepts/search-1/searchquery#reverse-includes), I think there is a bug.

_devbox; 0.4.9; bdf14e28;_

Steps to reproduce:
1. Create test data
```yaml
PUT /

- resourceType: Organization
  id: org-1
  name: Больница №9

- resourceType: Patient
  id: pt-1  
  name:
    - text: Иван Пантелеймонович Иванов
      given:
        - Иван
        - Пантелеймонович
      family: Иванов
  birthDate: '1970-01-01'
  managingOrganization:
    id: org-1
    resourceType: Organization

- resourceType: Condition
  id: cond-1
  clinicalStatus:
    coding:
      - code: active
        display: Активно (впервые)
  verificationStatus:
    coding:
      - code: confirmed
        display: Подтвержденное
  subject:
    id: pt-1
    resourceType: Patient
```

2. Then execute yaml below to debug SearchQuery
```yaml
POST /SearchQuery/$debug

# explain all queries
explain: true
# timeout for query in ms
timeout: 2000
# test with requests
tests:
  test1:
    params: {pid: 'pt-1'}
  
# SearchQuery definition
query:
  resource: {id: Patient, resourceType: Entity}
  as: pt
  total: true
  includes:
    organization:
      path: [managingOrganization]
      resource: {id: Organization, resourceType: Entity}
    conditions:
      reverse: true
      path: [subject]
      resource: {id: Condition, resourceType: Entity}
  params:
    pid: {type: string, isRequired: true, where: 'pt.id = {{params.pid}}'}
    ts: {type: date, where: 'pt.tis >= {{params.date}}'}
  query: {order-by: pt.ts desc}
  limit: 20
```

**Expected result:** it should return all three resources
**Actual result:** 2 resources, missing Condition resource
