### ISSUE TITLE
Access policies evaluation in transaction endpoint

### ISSUE THREAD

**Issue by yosbeleg89** [Aidbox/Issues#313]
When we are using the transaction endpoint, the policies are being evaluated using the whole Bundle as the resource? or each operation in transaction goes through same access control as if it was called independently?

If we make this request using `__debug=policy`:
```
POST /fhir?__debug=policy

{
    "resourceType": "Bundle",
    "type": "transaction",
    "entry": [{
        "resource": {
            "resourceType": "Appointment",
            "id": "ap1"
        },
        "request": {
            "method": "PUT",
            "url": "Appointment/ap1"
        }
    }
              ]
}
```

and we install the following AccessPolicy:
```
sql:
  query: >
    SELECT {{request-method}} = 'put'
    AND {{params.resource/type}}::text = 'Appointment'
    AND {{params.resource/id}}::text = 'ap1'
    AND {{body}}::jsonb    @> '{"resourceType": "Appointment"}'
engine: sql
id: test-appointment
resourceType: AccessPolicy
```

It seems like the `Bundle` is the one being evaluated:

```
- eval-result: false
  query:
  - |
    SELECT ? = 'put' AND ?::text = 'Appointment' AND ?::text = 'ap1' AND ?::jsonb::jsonb @> '{"resourceType":"Appointment"}'
  - post
  - null
  - null
  - '{"resourceType":"Bundle","type":"transaction","entry":[{"resource":{"resourceType":"Appointment","id":"ap1"},"request":{"method":"PUT","url":"Appointment/ap1"}}]}'
  id: test-appointment
  policy-id: test-appointment
```

Is there a way to evaluate each operation independently? and if it is being evaluated independently is it possible to see it in the debugging?
