### ISSUE TITLE
Error when expanding valueset based on SNOMED

### ISSUE THREAD

**Issue by orlandow** [Aidbox/Issues#317]
Aidbox Version: **0.5.0-SNAPSHOT**

### Step 1: Install SNOMED

following instructions from https://docs.aidbox.app/terminology/terminology-api#snomedct

<details>
  <summary>SNOMED Bundle</summary>
  <p>

```yaml
POST /
Content-Type: text/yaml

resourceType: Bundle
type: transaction
entry:
  - resource:
      resourceType: CodeSystem
      id: snomedct
      url: http://snomed.info/sct
      date: '2019-09-01'
      description: SNOMED CT is a standardized, multilingual vocabulary of clinical terminology
        that is used by physicians and other health care providers for the electronic exchange
        of clinical health information
      content: complete
      status: active
      version: snomed-version
    request:
      url: /CodeSystem/snomedct
      method: PUT

  - resource:
      resourceType: ValueSet
      id: snomedct
      description: This value set includes all RxNorm codes.
      version: snomed-version
      compose:
        include:
        - system: http://snomed.info/sct
      url: snomedct
      status: active
    request:
      url: /ValueSet/snomedct
      method: PUT

  - resource:
      id: snomedct
      inputFormat: application/fhir+ndjson
      contentEncoding: gzip
      mode: bulk
      inputs:
        - resourceType: Concept
          url: https://storage.googleapis.com/aidbox-public/fhir-terminology/snomedct-20190901.ndjson.gz
    request:
      url: /$import
      method: POST
```
  </p>
</details> 

### Step 2: Install Allergy Intolerance ValueSet

From https://www.hl7.org/fhir/valueset-allergyintolerance-code.html

<details>
  <summary>Allergy Intolerance ValueSet</summary>
  <p>

```yaml
resourceType: ValueSet
url: http://hl7.org/fhir/ValueSet/allergyintolerance-code
version: 4.0.1
name: AllergyIntoleranceSubstance/Product,ConditionAndNegationCodes
title: AllergyIntolerance Substance/Product, Condition and Negation Codes
status: draft
experimental: false
date: '2019-11-01T09:29:23+11:00'
publisher: FHIR Project team
contact:
- telecom:
  - system: url
    value: http://hl7.org/fhir
description: This value set includes concept codes for specific substances/pharmaceutical
  products, allergy or intolerance conditions, and negation/exclusion codes to specify
  the absence of specific types of allergies or intolerances.
copyright: This resource includes content from SNOMED Clinical TermsÂ® (SNOMED CTÂ®)
  which is copyright of the International Health Terminology Standards Development
  Organisation (IHTSDO). Implementers of these specifications must have the appropriate
  SNOMED CT Affiliate license - for more information contact http://www.snomed.org/snomed-ct/get-snomed-ct
  or info@snomed.org
compose:
  include:
  - valueSet:
    - http://hl7.org/fhir/ValueSet/substance-code
  - system: http://snomed.info/sct
    filter:
    - property: concept
      op: is-a
      value: '418038007'
  - system: http://snomed.info/sct
    filter:
    - property: concept
      op: is-a
      value: '267425008'
  - system: http://snomed.info/sct
    filter:
    - property: concept
      op: is-a
      value: '29736007'
  - system: http://snomed.info/sct
    filter:
    - property: concept
      op: is-a
      value: '340519003'
  - system: http://snomed.info/sct
    filter:
    - property: concept
      op: is-a
      value: '190753003'
  - system: http://snomed.info/sct
    filter:
    - property: concept
      op: is-a
      value: '413427002'
  - system: http://snomed.info/sct
    filter:
    - property: concept
      op: is-a
      value: '716186003'
```
  </p>
</details> 

### Step 3: Expand the ValueSet

<details>
  <summary>Entire output</summary>
  <p>

```yaml
description: This value set includes concept codes for specific substances/pharmaceutical products, allergy or intolerance conditions, and negation/exclusion codes to specify the absence of specific types of allergies or intolerances.
compose:
  include:
  - valueSet: ['http://hl7.org/fhir/ValueSet/substance-code']
  - filter:
    - {op: is-a, value: '418038007', property: concept}
    system: http://snomed.info/sct
  - filter:
    - {op: is-a, value: '267425008', property: concept}
    system: http://snomed.info/sct
  - filter:
    - {op: is-a, value: '29736007', property: concept}
    system: http://snomed.info/sct
  - filter:
    - {op: is-a, value: '340519003', property: concept}
    system: http://snomed.info/sct
  - filter:
    - {op: is-a, value: '190753003', property: concept}
    system: http://snomed.info/sct
  - filter:
    - {op: is-a, value: '413427002', property: concept}
    system: http://snomed.info/sct
  - filter:
    - {op: is-a, value: '716186003', property: concept}
    system: http://snomed.info/sct
date: '2019-11-01T09:29:23+11:00'
meta: {lastUpdated: '2020-06-25T22:13:10.330153Z', createdAt: '2020-06-25T22:13:10.330153Z', versionId: '1374'}
publisher: FHIR Project team
name: AllergyIntoleranceSubstance/Product,ConditionAndNegationCodes
copyright: This resource includes content from SNOMED Clinical TermsÂ® (SNOMED CTÂ®) which is copyright of the International Health Terminology Standards Development Organisation (IHTSDO). Implementers of these specifications must have the appropriate SNOMED CT Affiliate license - for more information contact http://www.snomed.org/snomed-ct/get-snomed-ct or info@snomed.org
experimental: false
resourceType: ValueSet
expansion:
  timestamp: 2020-06-25T22:13:22.696Z
  identifier: http://hl7.org/fhir/ValueSet/allergyintolerance-code
  contains:
    error: |-
      ERROR: syntax error at or near ")"
        Position: 72
title: AllergyIntolerance Substance/Product, Condition and Negation Codes
status: draft
id: allergy2
url: http://hl7.org/fhir/ValueSet/allergyintolerance-code
version: 4.0.1
contact:
- telecom:
  - {value: 'http://hl7.org/fhir', system: url}
```
  </p>
</details> 

```yaml
expansion:
  timestamp: 2020-06-25T22:13:22.696Z
  identifier: http://hl7.org/fhir/ValueSet/allergyintolerance-code
  contains:
    error: |-
      ERROR: syntax error at or near ")"
        Position: 72
```
