### ISSUE TITLE
ValueSet $expand returns error while browser view works (for concepts with valueset attribute provided)

### ISSUE THREAD

**Issue by pavlushkin** [Aidbox/Issues#321]
Hello!

It seems that something is broken or I don't get hot to use it.

There is a ValueSet
```yaml
url: 'https://api.domain.com/ValueSet/allergies'
name: allergies
title: allergies
status: active
experimental: true
id: allergies
resourceType: ValueSet
```
There is no `compose.include` data specified.

There is a concept
```yaml
code: '16224591000119103'
system: 'http://snomed.info/sct'
display: Allergy to honey bee venom
valueset:
  - allergies
id: snomed-16224591000119103
resourceType: Concept
```

I  see this concept in the list if I click on valuest name at http://localhost:8080/static/console.html#/entities/ValueSet?

However $expand returns an error `"No results were returned by the query."`
```yaml
name: allergies
experimental: true
resourceType: ValueSet
expansion:
  timestamp: 2020-06-25T06:58:54.126Z
  identifier: https://api.domain.com/ValueSet/allergies
  contains: {error: No results were returned by the query.}
title: allergies
status: active
id: allergies
url: https://api.domain.com/ValueSet/allergies
```

Should it work in this way?
