### ISSUE TITLE
json-patch doesn't work inside bundle

### ISSUE THREAD

**Issue by ir4y** [Aidbox/Issues#325]
```
POST /

type: batch
entry:
- method: PATCH
  request:
    url: "/Patient/bd2c780a-e30c-4f75-819e-93f1fd022fd7?_method=json-patch"
  resource:
  - op: add
    path: "/name"
    value:
    - text: "Patient name"
```

```
id: -1
type: batch-response
resourceType: Bundle
entry:
- resource:
    id: bd2c780a-e30c-4f75-819e-93f1fd022fd7
    resourceType: Patient
    meta: {lastUpdated: '2020-07-15T06:12:47.827949Z', createdAt: '2020-07-15T06:06:53.749052Z', versionId: '42479'}
  response: {etag: '42479', cache-control: no-cache, last-modified: 'Wed, 15 Jul 2020 06:12:47 GMT', x-duration: 52, x-request-id: 4bf8d7d1-841e-4fb7-830f-4a4577b9d749, status: '200'}
```
