### ISSUE TITLE
FHIRr4 :: Reference res :: support literal reference value

### ISSUE THREAD

**Issue by artemt-wa** [Aidbox/Issues#349]
Please support persistency and search by http://hl7.org/fhir/R4/references-definitions.html#Reference.reference

**Comment by Zallin** [comment]
Literal references are supported, you just have to use /fhir prefix for your query. Here is the quick example:

```
POST /Patient

id: 66cd493a-5dba-468b-a8fd-4dfbd1b19507
```

```
POST /Appointment 

status: pending
participant:
  - status: accepted
    actor:
      resourceType: Patient
      id: 66cd493a-5dba-468b-a8fd-4dfbd1b19507
```

`GET /fhir/Appointment` returns participant.actor.reference in correct FHIR format

let me know is this works for you and if you have additional questions
