### ISSUE TITLE
Logical Include does not work

### ISSUE THREAD

**Issue by pavlushkin** [Aidbox/Issues#360]
I use instructions at this page to write a GET request with logical inclusion:
https://docs.aidbox.app/basic-concepts/search-1/_include-and-_revinclude#logical-modifier

### Steps to reproduce:

1. Create a patient with an identifier:
```yaml
POST /Patient

id: test-patient
resourceType: Patient
name:
  - text: John Doe
gender: male
identifier:
  - value: testvalue
    system: custom/patient
```

2. Create an encounter with a logical reference to the patient:
```yaml
POST /Encounter

id: test-encounter
resourceType: Encounter
class:
  code: IMP
  system: 'http://terminology.hl7.org/CodeSystem/v3-ActCode'
  display: inpatient encounter
status: unknown
subject:
  identifier:
    value: testvalue
    system: custom/patient
```

3. Do a request with include
```yaml
GET /Encounter?_id=test-encounter&_include:logical=patient
```

### Actual result:
I get a bundle with the encounter without the patient
```yaml
query-time: 24
meta: {versionId: '808711'}
type: searchset
resourceType: Bundle
total: 1
link:
- {relation: first, url: '/Encounter?_id=test-encounter&_include:logical=patient&page=1'}
- {relation: self, url: '/Encounter?_id=test-encounter&_include:logical=patient&page=1'}
query-timeout: 60000
entry:
- resource:
    class: {code: IMP, system: 'http://terminology.hl7.org/CodeSystem/v3-ActCode', display: inpatient encounter}
    status: unknown
    subject:
      identifier: {value: testvalue, system: custom/patient}
    id: test-encounter
    resourceType: Encounter
    meta: {lastUpdated: '2021-02-08T06:44:29.736876Z', createdAt: '2021-02-08T06:44:29.736876Z', versionId: '808707'}
  fullUrl: http://localhost:8080/Encounter/test-encounter
  link:
  - {relation: self, url: 'http://localhost:8080/Encounter/test-encounter'}
query-sql: ['SELECT "encounter".* FROM "encounter" WHERE ("encounter".id in (?)) LIMIT ? OFFSET ? ', test-encounter, 100, 0]
```

### Expected result:
A bundle with two resources: encounter and patient.

---------

## Filtration is broken as well:

Do a request
```yaml
GET /Encounter?patient:Patient.identifier=testvalue
```
### Actual result:
```yaml
query-time: 92
meta: {versionId: '808713'}
type: searchset
resourceType: Bundle
total: 0
link:
- {relation: first, url: '/Encounter?patient:Patient.identifier=testvalue&page=1'}
- {relation: self, url: '/Encounter?patient:Patient.identifier=testvalue&page=1'}
query-timeout: 60000
entry: []
query-sql: ['SELECT * FROM (SELECT DISTINCT ON ("encounter".id) "encounter".* FROM "encounter" INNER JOIN patient j_5a2ef77e ON ("encounter".resource @> ($JSON${"subject":{"id":"$JSON$ || j_5a2ef77e.id || $JSON$","resourceType":"Patient"}}$JSON$)::jsonb) WHERE "j_5a2ef77e".resource @> ? ) "encounter" LIMIT ? OFFSET ?', '{"identifier":[{"value":"testvalue"}]}', 100, 0]
```

### Expected result:
A bundle with one resource: Encounter/test-encounter.

**Comment by KGOH** [comment]
You forgot to specify type of reference in `Encounter.subject`:

```
POST /Encounter

...
subject:
  type: Patient # <-- missing type here
  identifier:
    value: testvalue
    system: custom/patient
```
After this fix everything should start working

As for chained search, it seems, like there is no logic reference support right now
