### ISSUE TITLE
SearchQuery: add support for order-by params

### ISSUE THREAD

**Issue by Zallin** [Aidbox/Issues#366]
example of searchquery resource:
```yaml
params:
  order-direction:
    type: string
    format: '?'
    order-by: "appointment.resource->>'start' {{params.order-direction}}"
```

**Comment by rublag** [comment]
Added support for order-by in params. For order direction specified by params there are two approaches:

```yaml
params:
  order-direction:
    type: string
    format: '?'
    order-by: |
      CASE WHEN {{params.order-direction}} = 'asc' THEN ap.resource->>'start' END ASC,
      CASE WHEN {{params.order-direction}} = 'desc' THEN ap.resource->>'start' END DESC
```
Or
```yaml
params:
  ord-desc:
    type: string
    order-by: ap.resource->>'start' DESC
  ord-asc:
    type: string
    order-by: ap.resource->>'start' ASC
```
