### ISSUE TITLE
Extension converts from aidbox to fhir incorrectly

### ISSUE THREAD

**Issue by ir4y** [Aidbox/Issues#399]
**Urgency**
- [ ] minor
- [x] medium
- [ ] major
- [ ] critical
- [ ] show-stopper

**Steps to reproduce the behavior:**
Define extension on Questionnaire.item:
```json
{
            "Questionnaire.item.negationOption": {
                "path": ["item", "negationOption"],
                "resource": {"resourceType": "Entity", "id": "Questionnaire"},
                "extensionUrl": "negationOption",
            },
            "Questionnaire.item.negationOption.value": {
                "path": ["item", "negationOption", "value"],
                "resource": {"resourceType": "Entity", "id": "Questionnaire"},
                "extensionUrl": "negationOption",
                "isRequired": true,
            },
            "Questionnaire.item.negationOption.value.Coding": {
                "type": {"resourceType": "Entity", "id": "Coding"},
                "path": ["item", "negationOption", "value", "Coding"],
                "resource": {"resourceType": "Entity", "id": "Questionnaire"},
                "extensionUrl": "negationOption",
            },
}
```
Define Questionnaire
```yaml
item:
  - text: Diagnosis
    type: choice
    linkId: diagnosis-code
    required: true
    answerValueSet: acc-translation-table-map
    initialExpression:
      language: text/fhirpath
      expression: "item.where(linkId='diagnosis-code').answer.value.Coding"
  - text: Diagnosis side
    type: choice
    linkId: acc-diagnosis-side
    repeats: true
    required: true
    answerOption:
      - value:
          Coding:
            code: left
            system: 'https://www.acc.co.nz'
            display: Left
      - value:
          Coding:
            code: right
            system: 'https://www.acc.co.nz'
            display: Right
    negationOption:
      value:
        Coding:
          code: notApplicable
          system: 'https://www.acc.co.nz'
          display: Not Applicable
    initialExpression:
      language: text/fhirpath
      expression: "item.where(linkId='acc-diagnosis-side').answer.value.Coding"
  - text: Send to the ACC45 Claim
    type: boolean
    linkId: diagnosis-is-related-to-acc
    initial:
      - value:
          boolean: false
    initialExpression:
      language: text/fhirpath
      expression: "item.where(linkId='diagnosis-is-related-to-acc').answer.value.boolean"
  - text: Primary diagnosis
    type: boolean
    linkId: primary-diagnosis-indicator
    initial:
      - value:
          boolean: false
    initialExpression:
      language: text/fhirpath
      expression: "item.where(linkId='primary-diagnosis-indicator').answer.value.boolean"
status: active
id: 'acc-diagnosis'
resourceType: Questionnaire
meta:
  lastUpdated: '2021-07-01T07:19:29.848515Z'
  createdAt: '2021-01-18T13:00:43.456270Z'
  versionId: '277381'
```
Request Questionnaire in fhir format
```
GET /fhir/Questionnaire/acc-diagnosis
```

**Expected behavior**
```yaml
item:
  - text: Diagnosis
    type: choice
    linkId: diagnosis-code
    required: true
    answerValueSet: acc-translation-table-map
    extension:
      - url: 'http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-initialExpression'
        valueExpression:
          language: text/fhirpath
          expression: "item.where(linkId='diagnosis-code').answer.value.Coding"
  - text: Diagnosis side
    type: choice
    linkId: acc-diagnosis-side
    repeats: true
    required: true
    answerOption:
      - valueCoding:
          code: left
          system: 'https://www.acc.co.nz'
          display: Left
      - valueCoding:
          code: right
          system: 'https://www.acc.co.nz'
          display: Right
    extension:
      - url: negationOption
         valueCoding:
           code: notApplicable
           system: 'https://www.acc.co.nz'
           display: Not Applicable
      - url: 'http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-initialExpression'
        valueExpression:
          language: text/fhirpath
          expression: "item.where(linkId='acc-diagnosis-side').answer.value.Coding"
  - text: Send to the ACC45 Claim
    type: boolean
    linkId: diagnosis-is-related-to-acc
    initial:
      - valueBoolean: false
    extension:
      - url: 'http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-initialExpression'
        valueExpression:
          language: text/fhirpath
          expression: "item.where(linkId='diagnosis-is-related-to-acc').answer.value.boolean"
  - text: Primary diagnosis
    type: boolean
    linkId: primary-diagnosis-indicator
    initial:
      - valueBoolean: false
    extension:
      - url: 'http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-initialExpression'
        valueExpression:
          language: text/fhirpath
          expression: "item.where(linkId='primary-diagnosis-indicator').answer.value.boolean"
status: active
id: 'acc-diagnosis'
resourceType: Questionnaire
meta:
  lastUpdated: '2021-07-01T07:19:29.848515Z'
  versionId: '277381'
  extension:
    - url: 'ex:createdAt'
      valueInstant: '2021-01-18T13:00:43.456270Z'
```

**Actual behavior**
There are three nested 
```
    extension:
      - url: negationOption
```
```yaml
item:
  - text: Diagnosis
    type: choice
    linkId: diagnosis-code
    required: true
    answerValueSet: acc-translation-table-map
    extension:
      - url: 'http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-initialExpression'
        valueExpression:
          language: text/fhirpath
          expression: "item.where(linkId='diagnosis-code').answer.value.Coding"
  - text: Diagnosis side
    type: choice
    linkId: acc-diagnosis-side
    repeats: true
    required: true
    answerOption:
      - valueCoding:
          code: left
          system: 'https://www.acc.co.nz'
          display: Left
      - valueCoding:
          code: right
          system: 'https://www.acc.co.nz'
          display: Right
    extension:
      - url: negationOption
        extension:
          - url: negationOption
            extension:
              - url: negationOption
                valueCoding:
                  code: notApplicable
                  system: 'https://www.acc.co.nz'
                  display: Not Applicable
      - url: 'http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-initialExpression'
        valueExpression:
          language: text/fhirpath
          expression: "item.where(linkId='acc-diagnosis-side').answer.value.Coding"
  - text: Send to the ACC45 Claim
    type: boolean
    linkId: diagnosis-is-related-to-acc
    initial:
      - valueBoolean: false
    extension:
      - url: 'http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-initialExpression'
        valueExpression:
          language: text/fhirpath
          expression: "item.where(linkId='diagnosis-is-related-to-acc').answer.value.boolean"
  - text: Primary diagnosis
    type: boolean
    linkId: primary-diagnosis-indicator
    initial:
      - valueBoolean: false
    extension:
      - url: 'http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-initialExpression'
        valueExpression:
          language: text/fhirpath
          expression: "item.where(linkId='primary-diagnosis-indicator').answer.value.boolean"
status: active
id: 'acc-diagnosis'
resourceType: Questionnaire
meta:
  lastUpdated: '2021-07-01T07:19:29.848515Z'
  versionId: '277381'
  extension:
    - url: 'ex:createdAt'
      valueInstant: '2021-01-18T13:00:43.456270Z'
```
