### ISSUE TITLE
Console fails trying to display a resource with a `text` attribute

### ISSUE THREAD

**Issue by orlandow** [Aidbox/Issues#4]
Steps to reproduce:

Create an observation resource:

```
code:
  text: Body Weight
  coding:
    - code: 29463-7
      system: 'http://loinc.org'
text:
  div: 175 lbs
  status: generated
value:
  Quantity:
    unit: lbs
    value: 175
status: final
subject:
  id: pat1
  resourceType: Patient
id: obs1
resourceType: Observation
```

Navigate to the list page `/entities/Observation/`:

Fails with:

![image](https://user-images.githubusercontent.com/2000738/46418996-e58ac280-c6fa-11e8-84b0-d0fc5e846c5e.png)
