### ISSUE TITLE
Using AidboxQuery in the $dump-sql endpoint

### ISSUE THREAD

**Issue by Rende11** [Aidbox/Issues#408]
## Problem I need to solve
I want to generate reports with `POST /$dump-sql`. 
I suggest saving the SQL queries in Aidbox for their use in these reports.

## Solution I see
Provide an extension for  `POST /$dump-sql` like:

```
POST /$dump-sql

query-resource:
  resourceType: AidboxQuery
  id: patient-report
```
