### ISSUE TITLE
Nested attribute creation not working

### ISSUE THREAD

**Issue by orlandow** [Aidbox/Issues#41]
I'm creating an aidbox native extension (https://docs.aidbox.app/tutorials/working-with-extensions#aidbox-native-extensions)

If I create the attribute at the root level (like the example) it works fine. But when I nest it inside a backbone element and try to create the resource, I get the “extra property” error

this is my attribute definition:

```
PUT /Attribute/DocumentReference.content.text
Content-Type: application/yaml

module: onelogic-1.0
id: DocumentReference.content.text
resourceType: Attribute
resource:
  id: DocumentReference
  resourceType: Entity
path:
  - content
  - text
isRequired: false
isSummary: false
order: 100
type:
  id: string
  resourceType: Entity
description: Plaintext content of the document
```
