### ISSUE TITLE
Mapping: Unable to make patch query to remove attribute 

### ISSUE THREAD

**Issue by ruscoder** [Aidbox/Issues#416]
Hello! I use Mapping resource to make patch query for Encounter

```yaml
body:
  entry:
  - request:
     url: $ "/Encounter/" + encounterId
    method: PATCH
  resource:
    $if: $ diagnosesAnswers
    $then:
           diagnoses: [...el1, el2...]
       $else:
           diagnosis: []
```

As I know JUTE removes all empty values including empty arrays.

And in this example it makes my query with empty resource that leads to Aidbox error "Please provide body for patch"

Clearing empty values in JUTE was added before Aidbox started removing it and it was great feature. But now it seems like unneeded feature for JUTE

BTW, Aidbox clears empty value not like JUTE clears.

example:
```yaml
put /Patient/c5130691-0e3b-499d-9513-4dfd23ba6417
content-type: text/yaml
accept: text/yaml

name: [{text: null}]
```

output:

```yaml
name:
  - {}
id: c5130691-0e3b-499d-9513-4dfd23ba6417
resourceType: Patient
```

@mlapshin @niquola what do you think?

JUTE already provides function drop-blanks and wraps the JUTE evaluation result into it in the sources of Aidbox. What about removing this default behaviour or make it configurable at least for backward compatibility?

For now I can use json-patch as workaround.

[EDIT]
in some cases json-patch for my scenario does not work.

Json patch is quite simple and primitive. According to json-patch spec it is impossible to remove key that is not presented (e.g. Encounter without diagnosis).

And the query:
```yaml
- op: remove
   path: /diagnosis
```

fails.

Using json-patch + Aidbox it is possible to do a trick
```yaml
- op: add
   path: /diagnosis
   value: null
```

json-patch adds or replace diagnosis with null value, and Aidbox removes empty value on save

BUT! it is impossible to use it in Mapping, because JUTE remove empty values (value in my example) before evaluating and it leads to error again because value is mandatory for json-patch add op

Definetly need to re-consider clearing empty values in mapping since there're no workarounds left 🙁

**Comment by ruscoder** [comment]
Still an issue

**Comment by ruscoder** [comment]
Still an issue. Any updates on this?

**Comment by ruscoder** [comment]
Another clear and short example that does not work:
```
            - request:
                url: $ '/Patient/' + patientId
                method: PATCH
              resource:
                resourceType: "Patient"
                gender:
                  $if: $ gender
                  $then: $ gender
                  $else: null
```

Null is removed when gender is not provided and PATCH does not work
