### ISSUE TITLE
[BUG] Missing urlencode in bundle request url/headers

### ISSUE THREAD

**Issue by ruscoder** [Aidbox/Issues#437]
I encountered to an issue connected to the lack of urlencoding in JUTE bundles.

Usually, if I do get /User?email=my+email@gmail.com from rest console - it does not do urlencoding, and '+' sign in query string behaves like space ' ' character.
From a browser, querystring usually urlencoded and this query is encoded as  get /User?email=my%2bemail@gmail.com and it works correctly.

But if I make the same from JUTE:
```
resourceType: Bundle
type: batch
entry:
  - request:
      url: $ "/User?email=" + email
      method: POST
    fullUrl: urn:uuid:user-id
    resource:
      email: $ email
      resourceType: User
```

The email in the request url: $ "/User?email=" + email is not urlencoded

Without JUTE we have the same behaviour in Aidbox (pay attention on plus sign in resulting sql):

```
post /
content-type: text/yaml


resourceType: Bundle
type: transaction
entry:
  - request:
      url: /User?email=my+email@gmail.com
      method: GET
```

Result: "query-sql": [
     "SELECT \"user\".* FROM \"user\" WHERE \"user\".resource @> ? LIMIT ? OFFSET ? ",
     "{\"email\":\"my email@gmail.com\"}",

**Comment by ruscoder** [comment]
After discussion, decided to provide urlencode JUTE function to do this manually where it is needed:
```
resourceType: Bundle
type: batch
entry:
  - request:
      url: $ "/User?email=" + urlencode(email)
      method: POST
    fullUrl: urn:uuid:user-id
    resource:
      email: $ email
      resourceType: User
```

available in edge
