### ISSUE TITLE
[BUG] Bundle endpoint returns OperationOutcome w/o issue property if access denied

### ISSUE THREAD

**Issue by pavlushkin** [Aidbox/Issues#438]
**Bug description**
According to FHIR [OperationOtcome](https://www.hl7.org/fhir/operationoutcome.html) specification, 'issue' property is mandatory. We have found a case when we get an invalid OperationOtcome resource as a response.
It does not allow us to display a correct error on a frontend.

**Severity**
Normal

**Steps to reproduce the behavior:**

0. Add access policy that allows POST / but does not allow POST /Patient

1. Execute a query

```
POST /

resourceType: Bundle
type: 'transaction'
entry:
  - request:
      method: POST
      url: '/Patient'
    resource:
      name: 'test'
```

2. The response does not have 'issue' property
```
resourceType: OperationOutcome
id: '728989'
text:
  div: Transaction failed at entry[2]. Response status is 403. Response body is {"message":"Access
    Denied."}.

```

**Expected behavior**
Operation outcome with 'issue' specified as it done for other FHIR API endpoints like '/Patient'

 - Aidbox image version 2109
