### ISSUE TITLE
[BUG] `Bundle.entry.response.lastModified` wrong date format

### ISSUE THREAD

**Issue by KGOH** [Aidbox/Issues#443]
**Describe the bug**
Date returned in `lastModified` attribute of `POST /` response has format which is wrong by FHIR spec 

**Severity**
Medium

**Steps to reproduce the behavior:**
Execute following in Aidbox UI REST console:
```yaml
POST /

resourceType: Bundle
type: transaction
entry:
- request: {method: GET, url: "/Entity/Patient"}
```
Result will be
```yaml
resourceType: Bundle
type: transaction-response
entry:
  - resource:
      <...>
    response:
      etag: '0'
      lastModified: Thu, 11 Nov 2021 08:46:14 GMT
      status: '200'
```

**Expected behavior**
Get 
`Bundle.entry.resource.response.lastModified: 2021-11-11T08:46:14Z`

 - Aidbox image version
2109, 2110, stable, edge
