### ISSUE TITLE
[BUG] Cannot update HealthcareService resource

### ISSUE THREAD

**Issue by Soyoung7533** [Aidbox/Issues#447]
**Describe the bug**

We've been provided the resources for Touchstone Provider Directory API tests, which includes `HealthcareService/HospERService`. It currently uses `http://terminology.hl7.org/ValueSet/service-type` as the type coding system as below:
```
type:
  - coding:
      - code: '1'
        system: http://terminology.hl7.org/ValueSet/service-type
        display: Adoption/Permanent Care Info/Support
```

I tried to update it to `http://hl7.org/fhir/us/davinci-pdex-plan-net/ValueSet/HealthcareServiceTypeVS`. However, the update attempts fail and I cannot see why.

**Severity**
S1 - There are no ways to update the coding system of the type of `HealthcareService`.

**Steps to reproduce the behavior:**
1. Open Aidbox UI and find `HealthcareService/HospERService` resource
<img width="1302" alt="HealthcareService resource" src="https://user-images.githubusercontent.com/89491379/144149804-0da7cf80-b312-499e-9b1c-76490a83a021.png">
2. Update type.coding.system to `http://hl7.org/fhir/us/davinci-pdex-plan-net/ValueSet/HealthcareServiceTypeVS`

After the 'Save' button is pressed in Aidbox YAML format, the following errors occur:
```
resourceType: OperationOutcome
text:
  status: generated
  div: Invalid resource
issue:
  - severity: fatal
    code: invalid
    expression:
      - HealthcareService.deliverymethod.0.type
    diagnostics: ':type is required'
  - severity: fatal
    code: invalid
    expression:
      - HealthcareService.deliverymethod.0.extension
    diagnostics: unknown key :extension
```
After the 'Save' button is pressed in Fhir JSON format, following errors occur:
```
resourceType: OperationOutcome
text:
  status: generated
  div: Invalid resource
issue:
  - severity: fatal
    code: invalid
    expression:
      - HealthcareService.deliverymethod
    diagnostics: ':deliverymethod is required'
  - severity: fatal
    code: invalid
    expression:
      - HealthcareService.meta.extension.0.valueInstant
    diagnostics: unknown key :valueInstant
  - severity: fatal
    code: invalid
    expression:
      - HealthcareService.extension.0.extension.0.valueCodeableConcept
    diagnostics: unknown key :valueCodeableConcept
```

**Expected behavior**

**Screenshots**
ValueSet of HealthcareService type exists in the devbox:
<img width="1393" alt="ValueSet of HealthcareService type" src="https://user-images.githubusercontent.com/89491379/144150457-e040f595-1656-4f45-852e-647ad34a915a.png">

Error on the update attempt with YAML format
<img width="1379" alt="HealthcareService update yaml" src="https://user-images.githubusercontent.com/89491379/144150636-55d57d04-e139-4c82-a465-07d52cc402c3.png">

Error on the update attempt with FHIR JSON format
<img width="1392" alt="HealthcareService update fhir json" src="https://user-images.githubusercontent.com/89491379/144150649-1d40a425-5bc9-49f7-ba10-6e424adbbdfa.png">

**Versions:**
- OS version

- Docker version (if applicable)

 - Aidbox image version
 devbox:edge v:2111.151b06b8

 - Aidboxdb version (if applicable)

 - Browser version (if applicable)

 - Cloud provider (if applicable)

**Additional context**
Touchstone Conformance Test

Also scattered throughout a number of tests are warnings of the following type:

> WARNING: None of the codings provided are in the value set http://hl7.org/fhir/us/davinci-pdex-plan-net/ValueSet/HealthcareServiceTypeVS (http://hl7.org/fhir/us/davinci-pdex-plan-net/ValueSet/HealthcareServiceTypeVS), and a coding should come from this value set unless it has no suitable code (note that the validator cannot judge what is suitable) (codes = http://terminology.hl7.org/ValueSet/service-type#1). Location: Bundle.entry[2].resource.ofType(HealthcareService).type[0] (line 1, col 6916).
> Can the validator verify that the code you are using is from the HealthcareServiceType valueset?
 
https://touchstone.aegis.net/touchstone/scriptexecution?exec=202111301602358856812547&qn=/FHIR4-0-1-ProviderDir/DaVinci-PDEX-PlanNet/03-Query/dv-pdex-r4-03-PlanNet-03-Query-03-healthcareservice-json#WAITING_OPER
