### ISSUE TITLE
Mapping: JUTE: fhirpath looses original scope when context is passes

### ISSUE THREAD

**Issue by ruscoder** [Aidbox/Issues#449]
It seems a bug in passing a new scope when context passed as a second arg. 
It should merge context to the existing scope. Now it overrides.

Example of Mapping:
```
resourceType: Mapping
id: test
body:
 resultWithoutContext: $ fhirpath("a + b")
 resultWithContext: $ fhirpath("a + b + %context.c", myContext)
 ```

Payload (for aidbox console Mappers section):
```
- title: Example debug payload
  scope:
    a: 1
    b: 2
    myContext:
      c: 3
```

Result:
```
resultWithoutContext: 3
```

Expected:
```
resultWithoutContext: 3
resultWithContext: 6
```
