### ISSUE TITLE
Mapping: JUTE: fhirpath internal JUTE's scope is not passed into fhirpath scope

### ISSUE THREAD

**Issue by ruscoder** [Aidbox/Issues#450]
JUTE's scope that is defined in $let is not passed into fhirpath scope
```
resourceType: Mapping
id: test
body:
 $let:
   - myVar: 1
 $body:
   testContext: $ fhirpath("myVar")
   testEnv: $ fhirpath("%myVar")
```

I believe myVar should be accessible via env (%myVar) in the expression
