### ISSUE TITLE
References not translated depending on the order

### ISSUE THREAD

**Issue by hannmtz85** [Aidbox/Issues#46]
We are storing `DiagnosticReport` and `Observation` with reference between them, we are posting them to `/fhir` endpoint of aidbox server version `fhir-4.0.0`.

But we figure out that references are not translated if transaction bundle has `DiagnosticReport` first and then the `Observations`.

If instead we put the `Observations` first and then the `DiagnosticReport` the references are translated as well.

example.

This transaction works:

```
POST /
  Content-Type: application/yaml

  resourceType: Bundle
  type: transaction
  entry:
  - fullUrl: urn:uri:4a24d511-b568-4b89-b28c-ca932d82ec1f
    request:
      method: POST
      url: /Observation
    resource:
      status: final
      code:
        text: O
  - fullUrl: urn:uri:cfdeea4b-fc3d-43de-9bd8-bcf668c20ac1
    request:
      method: POST
      url: /DiagnosticReport
    resource:
      status: final
      code:
        text: D
      result:
        - uri: urn:uri:4a24d511-b568-4b89-b28c-ca932d82ec1f
```

And this not:

```
POST /
  Content-Type: application/yaml

  resourceType: Bundle
  type: transaction
  entry:
  - fullUrl: urn:uri:cfdeea4b-fc3d-43de-9bd8-bcf668c20ac1
    request:
      method: POST
      url: /DiagnosticReport
    resource:
      status: final
      code:
        text: D
      result:
        - uri: urn:uri:4a24d511-b568-4b89-b28c-ca932d82ec1f
  - fullUrl: urn:uri:4a24d511-b568-4b89-b28c-ca932d82ec1f
    request:
      method: POST
      url: /Observation
    resource:
      status: final
      code:
        text: O
```
