### ISSUE TITLE
[BUG] Non-existent valueset expansion returns 200

### ISSUE THREAD

**Issue by kzotoff** [Aidbox/Issues#465]
First, get any name which is not id of any ValueSet, for example, `something-that-does-not-exist`

Now `GET /ValueSet/something-that-does-not-exist/$expand`. Result will contain error message but HTTP result is 200.
But `GET /ValueSet/something-that-does-not-exist` returns 404.

It will be much more consistent if both requests will return 404.

**Comment by ddegr** [comment]
Fixed on `Aidbox:edge`

**Comment by Nesmeshnoy** [comment]
@kzotoff can you try it and let us know if it works as expected?

**Comment by kzotoff** [comment]
tested at devbox:edge v:2201.6bf1d78e

`GET /ValueSet/crazy/$expand`

Status: 404
message: ValueSet/crazy not found

**Comment by ruscoder** [comment]
The latest changes have broken POST ValueSet/$expand operation (example from doc https://docs.aidbox.app/terminology/valueset/value-set-expansion#valueset)

Example:
```
post /ValueSet/$expand

resourceType: Parameters
parameter:
- name: valueSet
  resource:
    resourceType: ValueSet
    compose:
      include:
        - system: http://snomed.info/sct
          concept:
            - code: '5000'
              display: Concept 5000
            - code: '1000'
              display: Concept 1000
            - code: '9000'
              display: Concept 9000
            - code: '2000'
              display: Concept 2000
            - code: '3000'
              display: Concept 3000
            - code: '11000'
              display: Concept 11000

```

Actual:
```
404

message: ValueSet/ not found
```

This worked on 2112.
