### ISSUE TITLE
[BUG] $dump returns resources with wrong type of versionId

### ISSUE THREAD

**Issue by ruscoder** [Aidbox/Issues#471]
```
get /User/$dump
```

returns
```
{"id": "...", "meta": {"createdAt": "2022-02-07T13:47:32.578740Z", "versionId": 2201, "lastUpdated": "2022-02-07T14:49:47.884691Z"}, "email": "...", "password": "...", "resourceType": "User"}
```

versionId is integer, but
```
get /User/...
```

returns
```
email: ...
password: ...
id: ...
resourceType: User
meta:
  lastUpdated: '2022-02-07T14:49:47.884691Z'
  createdAt: '2022-02-07T13:47:32.578740Z'
  versionId: '2201'
```

versionId is string.

It leads to some bugs on app side, when we fetch the whole resource and save it again:

```json
{"resourceType": "OperationOutcome", "text": {"status": "generated", "div": "Invalid resource"}, "issue": [
{"severity": "fatal", "code": "invalid", "expression": ["User.meta.versionId"], 
"diagnostics": "expected type of string"}], "id": "validationfail"}
```
