### ISSUE TITLE
[BUG] SQL engine interpolation failing on parameter with arary index in path

### ISSUE THREAD

**Issue by gravesee** [Aidbox/Issues#478]
**Describe the bug**
Trying to use a `..partOf.0.id` parameter in a request. The access policy does not interpolate the parameter value when using the sql engine -- it returns null.

**Severity**
Major

**Steps to reproduce the behavior:**
1. Create simple sql access policy

```yaml
test-sql-policy:
  engine: sql
  sql:
    query: |
      select {{params.\.partOf.0.id}}
```

2. Send request with `.partOf.0.id` parameter and `__debug=policy`:

`curl "http://localhost:8080/?.partOf.0.id=whatever&__debug=policy"`

3. Receive the following response '....'

### From the request property in debug response:
```json
       "params": {
            ".partOf.0.id": "whatever",
            "__debug": "policy"
        },
```

### From the evaluated policy in debug response:
```json 
        {
            "eval-result": null,
            "query": [
                "select ?\n",
                null
            ],
            "id": "test-sql-policy",
            "policy-id": "test-sql-policy"
        },
```

**Expected behavior**
Policy should correctly interpolate the value from the params property of the request.

**Versions:**
 - Aidbox image version: 0.5.0-SNAPSHOT

**Comment by KGOH** [comment]
Hello. You need to escape other `.` as well:

yaml example:
```yaml
sql:
  query: select {{params.\.partOf\.0\.id}}
engine: sql
```

json example:
```json
 "sql": {
  "query": "select {{params.\\.partOf\\.0\\.id}}"
 },
 "engine": "sql",
```
If escaping is done properly, this works as expected on `:edge`
