### ISSUE TITLE
[BUG] valueReferences malformed in sub-element Extensions

### ISSUE THREAD

**Issue by DMWhiteley** [Aidbox/Issues#479]
**Describe the bug**

`valueReference` elements included within an extension, where that extension is for a sub-element within a resource, do not prefix with the referenced resource's name. 

Those included within an extension where that extension is for the main resource, work correctly.

**Severity**

Major

**Steps to reproduce the behavior:**

Post the following Patient resource to devbox to see a reference which works, and one which doesn't.

```
POST /fhir/Patient
content-type: text/yaml
accept: text/yaml 

{
    "extension": [
      {
        "url": "http://working-organization-reference",
        "valueReference": {
          "reference": "Organization/91ac8681-4337-4c4d-a635-604719a90ef7"
        }
      }
    ],
    "id": "79bb2633-00b3-4c40-b7b9-628d072b87d2",
    "identifier": [
      {
        "extension": [
          {
            "url": "http://not-working-organization-reference",
            "valueReference": {
              "reference": "Organization/91ac8681-4337-4c4d-a635-604719a90ef7"
            }
          }
        ],
        "system": "random-identifier",
        "value": "1"
      }
    ],
    "meta": {
      "lastUpdated": "2019-01-10T10:00:00+00:00"
    },
    "name": [
      {
        "family": "Test",
        "given": [
          "Testing"
        ],
        "prefix": [
          "Mrs"
        ]
      }
    ],
    "resourceType": "Patient"
  }
  ```
Which results in the following output:
```
name:
  - given:
      - Testing
    family: Test
    prefix:
      - Mrs
extension:
  - url: http://working-organization-reference
    valueReference:
      reference: Organization/91ac8681-4337-4c4d-a635-604719a90ef7
identifier:
  - value: '1'
    system: random-identifier
    extension:
      - url: http://not-working-organization-reference
        valueReference:
          reference: /91ac8681-4337-4c4d-a635-604719a90ef7
id: 79bb2633-00b3-4c40-b7b9-628d072b87d2
resourceType: Patient
meta:
  lastUpdated: '2022-02-22T14:17:14.951950Z'
  versionId: '41'
  extension:
    - url: ex:createdAt
      valueInstant: '2022-02-22T14:17:14.951950Z'
```

**Expected behavior**

`valueReference` regardless of how used should always return a correctly-formed reference of resourceType/resourceId

**Versions:**

Using AIDBOX_FHIR_VERSION 3.0.1

 - Aidbox image version:
 
Latest edge: 372cfc949414553a7667b68be5b37a92b68fdd07c2e6b973554c3468faa62330
Also present on stable: 9152cd4b60d3a4f2700218c26c61c976e7333fb2643c084a74e90a26094247ee
