### ISSUE TITLE
[BUG] Identifier#assigner value silently not persisted to database

### ISSUE THREAD

**Issue by DMWhiteley** [Aidbox/Issues#486]
**Describe the bug**
1. Identifier#assigner is silently not being persisted, despite it being part of the core STU3 spec as per https://www.hl7.org/fhir/STU3/datatypes.html#identifier
2. When Identifier#assigner is for an Organization which does not exist, the resource is not rejected.

**Severity**
Major

**Steps to reproduce the behavior:**
Post the following Patient resource to devbox

```
POST /fhir/Patient
content-type: text/yaml
accept: text/yaml 

{
    "id": "79bb2633-00b3-4c40-b7b9-628d072b87d3",
    "identifier": [
      {
        "system": "random-identifier",
        "value": "1",
        "assigner": Organization/91ac8681-4337-4c4d-a635-604719a90ef7
      }
    ],
    "meta": {
      "lastUpdated": "2019-01-10T10:00:00+00:00"
    },
    "name": [
      {
        "family": "Test",
        "given": [
          "Testing"
        ],
        "prefix": [
          "Mrs"
        ]
      }
    ],
    "resourceType": "Patient"
  }
  ```
Which returns the following output
```
name:
  - given:
      - Testing
    family: Test
    prefix:
      - Mrs
identifier:
  - value: '1'
    system: random-identifier
id: 79bb2633-00b3-4c40-b7b9-628d072b87d3
resourceType: Patient
meta:
  lastUpdated: '2022-03-16T13:29:56.065963Z'
  versionId: '53'
  extension:
    - url: ex:createdAt
      valueInstant: '2022-03-16T13:29:56.065963Z'
```
Note identifier#assigner is missing. The POST also succeeds where it should have failed due to invalid reference.

**Expected behavior**
1. If the assigner Organization is not present, the resource should be rejected.
2. If the assigner Organization is present, assigner should be persisted and returned.

**Versions:**
Using AIDBOX_FHIR_VERSION 3.0.1

 - Aidbox image version:
Present on aidbox.app using :latest v:2202.0ea22ee9
