### ISSUE TITLE
[BUG] dateTime not parsed correctly

### ISSUE THREAD

**Issue by sneljasper** [Aidbox/Issues#508]
**Describe the bug**
dateTime regex does not match whole string, causing it to accept faulty input.

Changing
`^-?[0-9]{4}(-(0[1-9]|1[0-2])(-(0[0-9]|[1-2][0-9]|3[0-1])(T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\.[0-9]+)?(Z|(\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00)))?)?)?`
to
`^-?[0-9]{4}(-(0[1-9]|1[0-2])(-(0[0-9]|[1-2][0-9]|3[0-1])(T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\.[0-9]+)?(Z|(\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00)))?)?)?$`

fixes this (note `$` at the end).

**Severity**
Major

**Steps to reproduce the behavior:**
This request goes through succesfully:
```
POST /Schedule
content-type: application/json

{
 "actor": [
  {
   "reference": "Practitioner/some-practitioner"
  }
 ],
 "planningHorizon": {
  "end": "2022-05-11T17:00:03 sdoifhd",
  "start": "2022-05-11T17:00:03420"
 },
 "resourceType": "Schedule",
}
```

**Expected behavior**
```
422 
resourceType: OperationOutcome
text:
  status: generated
  div: Invalid resource
issue:
  - severity: fatal
    code: invalid
    expression:
      - Schedule.planningHorizon.end
    diagnostics: >-
      expected format
      ^-?[0-9]{4}(-(0[1-9]|1[0-2])(-(0[0-9]|[1-2][0-9]|3[0-1])(T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\.[0-9]+)?(Z|(\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00)))?)?)?$
```

**Versions:**

 - Aidbox image version:
  aidboxone:edge v:2204.123746db

**Additional context**
