### ISSUE TITLE
[BUG] GraphQL ConceptMap/ConceptMapList Query with group field from external client throws exception

### ISSUE THREAD

**Issue by rmhayek** [Aidbox/Issues#512]
**Describe the bug**
Query ConceptMap or ConceptMapList with a `group` field throws an exception using `Postman` or other external clients. It works fine from `http://localhost:8888/ui/graphql`.  The query is:
```
query {
  ConceptMapList {
    id
    group {
        source
        target
    }
  }
}
```
**Note** If the group is removed from the query, it responds correctly with the `id`(s)

**Severity**
Major

**Steps to reproduce the behavior:**
Use Postman, create a query to endpoint `http://localhost:8888/$graphql` with GraphQL content as shown above.  Set proper authorization and send.  The response is:
```
{
    "resourceType": "OperationOutcome",
    "id": "exception",
    "text": {
        "status": "generated",
        "div": "Exception in resolver for `ConceptMap/group': Key must be integer"
    },
    "issue": [
        {
            "severity": "fatal",
            "code": "exception",
            "diagnostics": "Exception in resolver for `ConceptMap/group': Key must be integer"
        }
    ]
}
```

**Expected behavior**
Return the group source/target.

**Screenshots**
![image](https://user-images.githubusercontent.com/72822589/170373453-218ebb1b-9ff5-4a57-8880-634446511251.png)

**Versions:**
devbox:edge v:2204.fedb6204

 - Aidbox image version:
edge

**Additional context**
N/A

**Comment by krevedkokun** [comment]
@rmhayek could you provide dump of your conceptmaprules?

**Comment by rmhayek** [comment]
@krevedkokun One of the community notebooks has a concept map that contains `group`:  

```
POST /fhir/ConceptMap
content-type: text/yaml
accept: text/yaml

resourceType: ConceptMap
id: "101"
url: http://hl7.org/fhir/ConceptMap/101
status: draft
sourceUri: http://hl7.org/fhir/ValueSet/address-use
targetUri: http://terminology.hl7.org/ValueSet/v3-AddressUse
group:
  - source: http://hl7.org/fhir/address-use
    target: http://terminology.hl7.org/CodeSystem/v3-AddressUse
    element:
      - code: home
        display: home
        target:
          - code: H
            display: home
            equivalence: equivalent
      - code: work
        display: work
        target:
          - code: WP
            display: work place
            equivalence: equivalent
      - code: temp
        display: temp
        target:
          - code: TMP
            display: temporary address
            equivalence: equivalent
      - code: old
        display: old
        target:
          - code: BAD
            display: bad address
            equivalence: disjoint
            comment: In the HL7 v3 AD, old is handled by the usablePeriod element, but you have to provide a time, there's no simple equivalent of flagging an address as old
```
