### ISSUE TITLE
[BUG] Azure SSO creates a new user after each login

### ISSUE THREAD

**Issue by pavlushkin** [Aidbox/Issues#525]
**Describe the bug**
I configured IdentityProvider for Azure AD:
```yaml
scopes:
  - profile
  - openid
system: az-dev
userinfo_endpoint: https://graph.microsoft.com/oidc/userinfo
authorize_endpoint: >-
  https://login.microsoftonline.com/7d4edb64/oauth2/v2.0/authorize
client:
  id: 07c17587
  secret: AW78Q
resourceType: IdentityProvider
title: Azure AD
active: true
id: azure-ad-dev
token_endpoint: >-
  https://login.microsoftonline.com/7d4edb64/oauth2/v2.0/token
```
Login with Azure ID works,
but after each login as admin I see a new user created.

User:
```yaml
data:
  sub: 1smMdvcWP876Y6d
  name: Aaa
  email: test@.onmicrosoft.com
  picture: https://graph.microsoft.com/v1.0/me/photo/$value
  given_name: Aa
  family_name: Bb
identifier:
  - value: 1smMdvcWP87
    system: az-dev
id: 12b44fd6-db22-4f07-b3e1-3dee45506365
resourceType: User
```

**Severity**

**Steps to reproduce the behavior:**

**Expected behavior**

I expect Aidbox not create user for the second and further logins

**Screenshots**

**Versions:**

 - Aidbox image version:
 

**Additional context**
