### ISSUE TITLE
404 while Okta sign-in [BUG]

### ISSUE THREAD

**Issue by pavlushkin** [Aidbox/Issues#528]
**Describe the bug**

I am implementing Okta authorization for Aidbox.
I follow the guide: https://docs.aidbox.app/security-and-access-control-1/auth/external-oauth-2.0-providers/configure-okta
While Okta OAuth2 flow I get 404 error

**Severity**

Minor

**Steps to reproduce the behavior:**

1. Register Okta account and application with settings:

<img width="734" alt="image" src="https://user-images.githubusercontent.com/31745899/183395383-3a913a81-d3b4-432c-882c-3a5f73fd9ba5.png">

<img width="725" alt="image" src="https://user-images.githubusercontent.com/31745899/183395444-e1c2258d-ce42-4ed6-9dcb-912885c6926a.png">

2. Create IdentityProvider
```yaml
scopes:
  - profile
  - openid
system: okta
userinfo_endpoint: https://dev-36416771-admin.okta.com/oauth2/v1/userinfo
authorize_endpoint: https://dev-36416771-admin.okta.com/oauth2/v1/authorize
client:
  id: 0oa1wjk6glw7y8nYV***
  secret: ********
  redirect_uri: https://aidbox.is-dev.beda-software/auth/callback/okta
resourceType: IdentityProvider
title: MyOkta
active: true
id: okta
token_endpoint: https://trial-5396993-admin.okta.com/oauth2/v1/token
```

3. Click "Signin with MyOkta"

4. Got:
`https://dev-36416771-admin.okta.com/error/404?fromURI=%2Foauth2%2Fv1%2Fauthorize%3Fresponse_type%3Dcode%26scope%3Dprofile%2Bopenid%26client_id%3D0oa1wjk6glw7y8nYV697%26redirect_uri%3Dhttps%253A%252F%252Faidbox.is-dev.beda-software%252Fauth%252Fcallback%252Fokta%26state%3DP25vbmU9bm9uZQ%253D%253D`

<img width="431" alt="image" src="https://user-images.githubusercontent.com/31745899/183395929-e2e19704-3d68-4002-b41a-78219140e99f.png">

**Expected behavior**

Okta login page

**Screenshots**

**Versions:**

 - Aidbox image version:
 
aidboxone:stable
v:2112.e85b35a5

**Additional context**
