### ISSUE TITLE
Having problem while creating Search Parameter

### ISSUE THREAD

**Issue by ghost** [Aidbox/Issues#530]
Hi, I trying to create new SearchParameter but I having an issue. 

I couldn't understand  why it  **Could not resolve element for expression ["patient"]** ?

> My request
```yaml
PUT /SearchParameter/TrainingSchedules.patient
content-type: text/yaml
accept: text/yaml

name: patient
type: token
resource: {id: TrainingSchedules, resourceType: Entity}
expression: [[patient]] ```

> The response
```yaml 
resourceType: OperationOutcome
text:
  status: generated
  div: Invalid resource
issue:
  - severity: fatal
    code: invalid
    expression:
      - SearchParameter.
    diagnostics: Could not resolve element for expression ["patient"]
```

> And my TrainingSchedules structure is 

TrainingSchedules.days | string [ ] | A list of available days
-- | -- | --

TrainingSchedules.id | string
-- | --

TrainingSchedules.patient* | Reference | Owner of the schedule
-- | -- | --

> The structure of  patient attribute 

``` yaml
description: Owner of the schedule
path:
  - patient
refers:
  - Patient
type:
  id: Reference
  resourceType: Entity
resourceType: Attribute
module: fhir-4.0.1
id: TrainingSchedules.patient
resource:
  id: TrainingSchedules
  resourceType: Entity
order: 12
isRequired: true
_source: code
isSummary: true

```
