### ISSUE TITLE
Support specifying :zen.fhir/type "Resource"

### ISSUE THREAD

**Issue by ir4y** [Aidbox/Issues#549]
Profile definition
```
 ResourceProfile
 {:zen/tags #{zen.fhir/profile-schema zen/schema}

  :confirms #{hl7-fhir-r4-core.Resource/schema}
  :zen.fhir/type "Resource"
  :zen.fhir/profileUri "urn:profile:heal:Resource"
  :type zen/map
  :zen.fhir/version "0.5.20"
  :keys {:meta {:type zen/map
                :keys {:tenantId {:fhir/extensionUri "urn:extension:heal:tenantId"
                                  :confirms #{hl7-fhir-r4-core.string/schema}}}}}}
```

Resource definition
```
code:
  coding:
    - code: '1187310'
      system: http://www.nlm.nih.gov/research/umls/rxnorm
      display: Tylenol Oral Liquid Product
    - code: '476856'
      system: https://www.fdbhealth.com
      display: Child's Tylenol plus Cough,Runny Nose 1 mg-5 mg-160 mg/5 mL oral susp
meta:
  profile:
    - urn:profile:heal:Resource
    - http://hl7.org/fhir/us/core/StructureDefinition/us-core-medication
  tenantId: '1'
  lastUpdated: '2022-11-18T09:31:46.392251Z'
  createdAt: '2022-11-18T09:31:46.392251Z'
  versionId: '367'
status: active
id: med-1
resourceType: Medication
```

<img width="803" alt="Screenshot 2022-11-18 at 15 11 42" src="https://user-images.githubusercontent.com/1488983/202692403-5844c2db-c213-489b-851a-b0f0eef8bd6b.png">
