### ISSUE TITLE
Custom operation invalid JSON response

### ISSUE THREAD

**Issue by pavlushkin** [Aidbox/Issues#553]
## Question

Hello! I make a custom operation call with invalid JSON and get inconsistent behavior for a client:

## Request:
```yaml
PUT /$load-observations
content-type: application/json
accept: application/json

{"x": NaN}
```

## Actual Aidbox behavior:
- The request is not passed to Aidbox App operation handler.
- No log record registered in Elasticsearch
- Response Status Code: 500
- Response text:
  ```clojure
  Non-standard token 'NaN': enable JsonParser.Feature.ALLOW_NON_NUMERIC_NUMBERS to allow
   at [Source: (BufferedReader); line: 1, column: 10]
  ```

## Desired behavior:
- Aidbox proxies the request to Aidbox App operation handler.
- App validates invalid JSON and returns 422

## Question:
How can I get desired behavior?
