### ISSUE TITLE
Create flat views with View Definitions on startup app

### ISSUE THREAD

**Issue by zakharych** [Aidbox/Issues#569]
## Question
Hi, I am attempting to create flat views using View Definitions upon application startup. 
I am using the aidbox-python-sdk, not the Zen project. 
I create ViewDefinitions.yaml resources similar to my other resources such as Mappings and AidboxQueries.

However, upon app startup, only the ViewDefinition resource is available, and a flat view isn't created. When I attempt to execute select * from ```sof.my_view_name```, I receive an error ```sof.my_view_name not found```.

The flat view is only generated when I click the 'save' button in the View Definitions tab for my resource.

How can I create View Definitions and flat views during app initialization? I require this for automatically testing my queries.

**Comment by Nesmeshnoy** [comment]
@zakharych what is your Aidbox version? This behavior was fixed in Aidbox's September [2109](https://docs.aidbox.app/overview/release-notes#september-2023-2309) release.

Could you please share the ViewDefinitons you're working with? It'll help us to reproduce.

**Comment by zakharych** [comment]
@Nesmeshnoy  
Aidbox version - 2311
Exact message error ```ERROR: relation "sof.test_patient_view" does not exist```

ViewDefenition resource:
```
name: test_patient_view
resource: Patient
description: Patient flat view
status: active
extension:
  - url: materialization
    value:
      code: view
select:
  - alias: id
    path: id
  - alias: bod
    path: birthDate
  - alias: gender
    path: gender

```
