### ISSUE TITLE
Problem when deploying aidbox in kubernetes environement with test license: 

### ISSUE THREAD

**Issue by ghaliouss** [Aidbox/Issues#576]
## Question

We are trying to test aidbox and install it in our kubernetes environement. we adapt the manifest files and deployed it but we are facing a problem with the deploy of the pod, we have this error message:

```
:get-key "license/public-keys/.key.pub" #error {
 :cause "Cannot open <nil> as a Reader."
 :via
 [{:type java.lang.IllegalArgumentException
   :message "Cannot open <nil> as a Reader."
   :at [clojure.java.io$fn__11641 invokeStatic "io.clj" 288]}]
 :trace
 [[clojure.java.io$fn__11641 invokeStatic "io.clj" 288]
  [clojure.java.io$fn__11641 invoke "io.clj" 288]
  [clojure.java.io$fn__11530$G__11519__11537 invoke "io.clj" 69]
  [clojure.java.io$reader invokeStatic "io.clj" 102]
  [clojure.java.io$reader doInvoke "io.clj" 86]
  [clojure.lang.RestFn invoke "RestFn.java" 410]
  [clojure.lang.AFn applyToHelper "AFn.java" 154]
  [clojure.lang.RestFn applyTo "RestFn.java" 132]
  [clojure.core$apply invokeStatic "core.clj" 669]
  [clojure.core$slurp invokeStatic "core.clj" 7010]
  [clojure.core$slurp doInvoke "core.clj" 7010]
  [clojure.lang.RestFn invoke "RestFn.java" 410]
  [license.utils$fn__68028 invokeStatic "utils.clj" 50]
  [license.utils$fn__68028 invoke "utils.clj" 49]
  [clojure.lang.AFn applyToHelper "AFn.java" 154]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.core$apply invokeStatic "core.clj" 667]
  [clojure.core$memoize$fn__6946 doInvoke "core.clj" 6389]
  [clojure.lang.RestFn invoke "RestFn.java" 408]
  [license.utils$verify_jwt_modern invokeStatic "utils.clj" 68]
  [license.utils$verify_jwt_modern invoke "utils.clj" 61]
  [license.modern$issue_instance_token invokeStatic "modern.clj" 55]
  [license.modern$issue_instance_token invoke "modern.clj" 42]
  [license.modern$update_license_state_BANG_$fn__68174 invoke "modern.clj" 172]
  [license.modern$update_license_state_BANG_ invokeStatic "modern.clj" 169]
  [license.modern$update_license_state_BANG_ doInvoke "modern.clj" 154]
  [clojure.lang.RestFn invoke "RestFn.java" 442]
  [license.modern$start_license_check_service invokeStatic "modern.clj" 551]
  [license.modern$start_license_check_service doInvoke "modern.clj" 547]
  [clojure.lang.RestFn invoke "RestFn.java" 442]
  [license.modern$check_license invokeStatic "modern.clj" 587]

```
![image](https://github.com/Aidbox/Issues/assets/14861910/ac4f464b-a0b1-4383-a61e-87c4d24cf34c)

It seems there is a problem with the license which is a personal test license for dev that i generate it from your website.
I also checked the database and the table is empty:

![image](https://github.com/Aidbox/Issues/assets/14861910/437423f2-8403-42eb-8070-0c3ebc872441)

Can you help please ?

Thanks in advance.

**Comment by Nesmeshnoy** [comment]
hey @ghaliouss can you share the configs? it'll help.

I'd also mention this guide for your reference https://docs.aidbox.app/getting-started/run-aidbox-in-kubernetes/deploy-aidbox-in-kubernetes

**Comment by ghaliouss** [comment]
> hey @ghaliouss can you share the configs? it'll help.
> 
> I'd also mention this guide for your reference https://docs.aidbox.app/getting-started/run-aidbox-in-kubernetes/deploy-aidbox-in-kubernetes

Hello @Nesmeshnoy , thanks for your answer.

here my both manifest files: deployment.yml and configmap.yml for the aidbox service:

```yaml
 name: aidbox
  labels:
    app: aidbox
    component: front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aidbox
      component: front
  template:
    metadata:
      labels:
        app: aidbox
        component: front
    spec:
      containers:
        - name: main
          image: healthsamurai/aidboxone:edge
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8765
              protocol: TCP
          envFrom:
            - configMapRef:
                name: aidbox
```

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: aidbox
data:
  AIDBOX_BASE_URL: "XXXXX"
  AIDBOX_BOX_ID: aidbox
  AIDBOX_FHIR_VERSION: 4.0.1
  AIDBOX_PORT: '8080'
  AIDBOX_STDOUT_PRETTY: all
  BOX_INSTANCE_NAME: aidbox
  BOX_METRICS_PORT: '8765'
  PGDATABASE: aidbox
  PGHOST: aidbox-db   # database address
  PGPORT: '5432'
  AIDBOX_TERMINOLOGY_SERVICE_BASE_URL: "https://tx.fhir.org/r4"
  AIDBOX_FHIR_PACKAGES: "hl7.fhir.r4.core#4.0.1"
  AIDBOX_COMPLIANCE: "enabled"
  AIDBOX_FHIR_SCHEMA_VALIDATION: "true"
  AIDBOX_CREATED_AT_URL: "https://aidbox.app/ex/createdAt"
  AIDBOX_CORRECT_AIDBOX_FORMAT: "true"
  BOX_SEARCH_FHIR__COMPARISONS: "true"
  BOX_PROJECT_GIT_URL: "https://github.com/Aidbox/aidbox-project-template.git"
  BOX_PROJECT_GIT_PROTOCOL: "https"
  BOX_PROJECT_GIT_TARGET__PATH: "/tmp/aidbox-project"
  BOX_PROJECT_GIT_CHECKOUT: "main"
  AIDBOX_ZEN_ENTRYPOINT: "main/box"
  AIDBOX_DEV_MODE: "true"
  AIDBOX_ZEN_DEV_MODE: "true"
  BOX_AUTH_KEYS_SECRET: "auth-key-secret"
  BOX_AUTH_KEYS_PRIVATE: "XXXX"
  BOX_AUTH_KEYS_PUBLIC: "XXXXX"
  AIDBOX_ADMIN_PASSWORD: "XXX"
  AIDBOX_CLIENT_SECRET: "XXX"
  PGUSER: "postgres"
  PGPASSWORD: "XXXX"
  AIDBOX_LICENSE: "XXXX"
```
